name: development

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["run"]
    branches: [master]
    types: [completed]
  # make it so it runs on push to master
  push:
    branches: [master]
  # make it so it runs every 5 hours
  # schedule:
  #   - cron: "0 */5 * * *"

jobs:
  run:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create environment file
        run: echo "DISCORDJS_BOT_TOKEN=${{ env.DISCORDJS_BOT_TOKEN }}" > .env
      
      - name: Show environment file
        run: cat .env

      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v2
        with:
          node-version: "16.16.0"

      - name: Install dependencies
        run: npm install

      - name: Run bot
        run: npm start
