name: run

on:
    workflow_dispatch:
    # Make it so it runs if bot crashes
    workflow_run:
        workflows: ["run"]
        types: [completed]

jobs:
    # run. Keep in mind that we are using node.js v16.16.0
    run:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16.16.0
              uses: actions/setup-node@v2
              with:
                  node-version: "16.16.0"
            - name: Install dependencies
              run: npm install
            - name: Run bot
              run: npm start